#include <iostream>

/* including config generated by cmake */
#include "TestConfig.h"
#include "GitSHA1.h"

using namespace std;

int main(int argc, const char *args[])
{
    cout << "Test program to test building system cmake" << endl;
    cout << "Builded from commit:" << getGitSHA1() << endl;
    return 0;
}
