#include <iostream>

/* including config generated by cmake */
#include "TestConfig.h"

using namespace std;

int main(int argc,const char * args[] )
{
  cout << "Test program to test building system cmake" << endl;
  return 0;
}
